spring:
  config:
    use-legacy-processing: true
    activate:
      on-profile: production
    import: 'aws-parameterstore'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: seb43main029


#config:
#  domain: http://seb43-main-029-client.s3-website.ap-northeast-2.amazonaws.com