spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://seb43main029.cafsp4hphkci.ap-northeast-2.rds.amazonaws.com:13306/application?serverTimezone=Asia/Seoul
    username: ${JDBC_USERNAME}
    password: 29main!!

  config:
    use-legacy-processing: true

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace

config:
  domain: http://seb43-main-029-client.s3-website.ap-northeast-2.amazonaws.com

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: KaPdSgVkXp2s5v8y/B?E(H+MbQeThWmZ #${JWT_SECRET_KEY}
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: seb43main029
  ssm:
    enabled: true

cloud:
  aws:
    s3:
      bucket: seb43-main-029-images
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIAVKPGHUCTDGWQDJEA
      secret-key: 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