version: 0.2

env:
  parameter-store:
    #JDBC_URL: /config/seb43main029/jdbc.url
    #JDBC_USERNAME: /config/seb43main029/jdbc.username
    JDBC_PASSWORD: /config/seb43main029/jdbc.password

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd server
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./server/build/libs/*.jar)
artifacts:
  files:
    - server/build/libs/*.jar
    - server/scripts/**
    - server/appspec.yml
  discard-paths: yes